// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhSja5MIeaMUIKln69fWDnznKCbeJMskQ',
    appId: '1:296210165303:android:ec5eb318678d239f58d9b2',
    messagingSenderId: '296210165303',
    projectId: 'subrate-91f04',
    storageBucket: 'subrate-91f04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo1aVDVbUOrDLmZUDAYIQqr500_E_ZGss',
    appId: '1:296210165303:ios:ed6dfeac904c122958d9b2',
    messagingSenderId: '296210165303',
    projectId: 'subrate-91f04',
    storageBucket: 'subrate-91f04.firebasestorage.app',
    androidClientId: '296210165303-614bjevpieeto3ojot3pas7t3r4i8436.apps.googleusercontent.com',
    iosClientId: '296210165303-l0nr0is03rjf130in1k5hmahiievhprs.apps.googleusercontent.com',
    iosBundleId: 'com.projecxio.subrate',
  );

}